"""init

Revision ID: 48a44d0dcd5a
Revises: 
Create Date: 2024-12-04 22:11:23.107408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a44d0dcd5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fclty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=100), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('idnum', sa.String(length=200), nullable=True),
    sa.Column('campus', sa.String(length=200), nullable=False),
    sa.Column('college', sa.String(length=200), nullable=False),
    sa.Column('program', sa.String(length=200), nullable=False),
    sa.Column('year', sa.String(length=200), nullable=False),
    sa.Column('faculty', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prgrms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=100), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('faculty', sa.String(length=200), nullable=False),
    sa.Column('qletter', sa.String(length=200), nullable=False),
    sa.Column('qid', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['input_data.email'], ),
    sa.ForeignKeyConstraint(['faculty'], ['input_data.faculty'], ),
    sa.ForeignKeyConstraint(['qid'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('user')
    op.drop_table('question_d')
    op.drop_table('question_c')
    op.drop_table('question_b')
    op.drop_table('question')
    op.drop_table('prgrms')
    op.drop_table('input_data')
    op.drop_table('fclty')
    op.drop_table('college')
    op.drop_table('campus')
    # ### end Alembic commands ###
